language: php
php:
  - 5.5
  - 5.6
before_script:
  - composer self-update
  - composer install --dev
script:
  - mkdir -p build/logs
after_script:
  - php vendor/bin/phpcs gomoku.php --standard=PSR2
  - php vendor/bin/phpcpd gomoku.php
