language: php
php:
  - 5.5
  - 5.6
  - hhvm
before_script:
  - composer self-update
  - composer install
script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit -c ./phpunit.xml --coverage-clover ./build/logs/clover.xml
after_script:
  - php vendor/bin/coveralls -v -c .coveralls.yml
  - php vendor/bin/phpcs gomoku.php --standard=PSR2
  - php vendor/bin/phpcpd gomoku.php
  - php vendor/bin/phpmd gomoku.php text codesize,controversial,design,naming,unusedcode
